CREATE USER  @db.user@ 
IDENTIFIED BY @db.password@
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
/
GRANT CREATE SESSION TO @db.user@
/
GRANT CREATE TABLE TO @db.user@
/
GRANT CREATE PROCEDURE TO @db.user@
/
GRANT CREATE TRIGGER TO @db.user@
/
GRANT CREATE VIEW TO @db.user@
/
GRANT CREATE SEQUENCE TO @db.user@
/
GRANT CREATE VIEW TO @db.user@
/
GRANT DELETE ANY TABLE TO @db.user@
/
GRANT DROP ANY TABLE TO @db.user@
/
GRANT DROP ANY PROCEDURE TO @db.user@
/
GRANT DROP ANY TRIGGER TO @db.user@
/
GRANT DROP ANY VIEW TO @db.user@
/
GRANT ALTER ANY TABLE TO @db.user@
/
GRANT ALTER ANY TABLE TO @db.user@
/
GRANT ALTER ANY PROCEDURE TO @db.user@
/
GRANT ALTER ANY TRIGGER TO @db.user@
/
GRANT UNLIMITED TABLESPACE TO @db.user@
/
COMMIT
/
