CREATE USER  OMPTEST2 
IDENTIFIED BY test
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
/
GRANT CREATE SESSION TO OMPTEST2
/
GRANT CREATE TABLE TO OMPTEST2
/
GRANT CREATE PROCEDURE TO OMPTEST2
/
GRANT CREATE TRIGGER TO OMPTEST2
/
GRANT CREATE VIEW TO OMPTEST2
/
GRANT CREATE SEQUENCE TO OMPTEST2
/
GRANT CREATE VIEW TO OMPTEST2
/
GRANT DELETE ANY TABLE TO OMPTEST2
/
GRANT DROP ANY TABLE TO OMPTEST2
/
GRANT DROP ANY PROCEDURE TO OMPTEST2
/
GRANT DROP ANY TRIGGER TO OMPTEST2
/
GRANT DROP ANY VIEW TO OMPTEST2
/
GRANT ALTER ANY TABLE TO OMPTEST2
/
GRANT ALTER ANY TABLE TO OMPTEST2
/
GRANT ALTER ANY PROCEDURE TO OMPTEST2
/
GRANT ALTER ANY TRIGGER TO OMPTEST2
/
GRANT UNLIMITED TABLESPACE TO OMPTEST2
/
COMMIT
/
